#!/usr/bin/env python
"""HTTPing


Usage:
    httping <url> [-H] [--interval=<seconds>]
    httping -h | --help

Options:
    -h --help                Show this screen.
    -H --headers             Show the headers returned by each request.
    -i --interval=<seconds>  Time between requests, in seconds. [default: 1]
"""

from docopt import docopt
import requests
from datetime import datetime
from time import sleep

def main(url, interval=None, show_headers=False):
    if not interval:
        interval = 1

    while 1:
        now = datetime.now()
        r = requests.get(url)
        error = ''
        if r.error:
            error = ' ({})'.format(r.error)

        print "{}: [{}] {}{}".format(
            now.strftime('%Y-%m-%d %H:%M:%S.%f'),
            r.status_code,
            url,
            error
        )
        if show_headers:
            for k, v in r.headers.items():
                print '    {}: {}'.format(
                    k.upper(),
                    v
                )
        sleep(interval)

if __name__ == '__main__':
    args = docopt(__doc__, version='HTTPing 0.1')
    try:
        interval = float(args['--interval'])
    except ValueError:
        interval = 1
    main(args['<url>'], interval=interval,
         show_headers=args['--headers'])
