#!/usr/bin/env python
"""hping - a simple tool to hit websites at a given interval and display
whether they are up or not.

Usage:
    hping <url> [-H] [--interval=<seconds>]
    hping -h | --help

Options:
    -h --help                Show this screen.
    -H --headers             Show the headers returned by each request.
    -i --interval=<seconds>  Time between requests, in seconds. [default: 1]
"""

import signal
import sys
from docopt import docopt

from hping import hping

def signal_handler(signal, frame):
    sys.exit(0)


if __name__ == '__main__':
    args = docopt(__doc__, version='hping 0.1')
    try:
        interval = float(args['--interval'])
    except ValueError:
        interval = 1
    signal.signal(signal.SIGINT, signal_handler)
    hping(args['<url>'], interval=interval,
         show_headers=args['--headers'])

    signal.pause()