#!/usr/bin/env python
"""pyhp - a simple tool to hit websites at a given interval and display
whether they are up or not.

Usage:
    pyhp <url> [-H] [--interval=<seconds>]
    pyhp -h | --help

Options:
    -h --help                Show this screen.
    -H --headers             Show the headers returned by each request.
    -i --interval=<seconds>  Time between requests, in seconds. [default: 1]
"""

import signal
import sys
from docopt import docopt

from pyhp import pyhp

def signal_handler(signal, frame):
    sys.exit(0)


if __name__ == '__main__':
    args = docopt(__doc__, version='pyhp 0.1')
    signal.signal(signal.SIGINT, signal_handler)

    try:
        interval = float(args['--interval'])
    except ValueError:
        interval = 1

    for line in pyhp(args['<url>'], interval=interval,
        show_headers=args['--headers']):
        print line
        sys.stdout.flush()

    signal.pause()
